### ISSUE TITLE
some words are not parsed correctly due to tag <BR>

### ISSUE THREAD

**Issue by DerekGeng** [mwaldstein/edgarWebR#2]
in the function , **parse_filings**, some words are still connected to each other such as "Weightedaverageexerciseprice" after parsing. This means it cannot recognize this as a proper word. 
In the original html document, it is expressed as Weighted<BR>average<BR>exercise<BR>price, this indicates that parse_filings function cannot recognize the <BR> properly. 

pls fix this and many thx!

**Comment by mwaldstein** [comment]
Thanks for finding this - could you share a filing that shows this behavior?

**Comment by DerekGeng** [comment]
it cannot parse properly if <BR> exist between the words, after parsing, the words stick together as one "word", 
see below the link: 
https://www.sec.gov/Archives/edgar/data/1399855/000119312514363235/0001193125-14-363235.txt

looking forward to your reply!

**Comment by DerekGeng** [comment]
sry, again, it cannot parse properly if "<BR>"
exist between the words in html format.

Thx in advance!

**Comment by DerekGeng** [comment]
sry, again, it cannot parse properly if `<BR>`
exist between the words.

**Comment by mwaldstein** [comment]
Ok - shouldn't be too difficult to fix. I'll update when fixed.

**Comment by mwaldstein** [comment]
All fixed. You can use it directly from github for now, the next release to CRAN should be early next week.
