### ISSUE TITLE
Documentation: Docuement how 'Fast Search' works and is implemented in edgarWebR

### ISSUE THREAD

**Issue by proverbs53** [mwaldstein/edgarWebR#7]
Edgar website allows to search by either the name (regular search) or by CIK/Ticker symbol (Fast Search).
https://www.sec.gov/edgar/searchedgar/companysearch.html

I would love to have company_search() extended with a CIK=TRUE/FALSE parameter, and something like the following logic:

    ifelse(CIK,
          ifelse(file_number,
                 paste0("&company=&filenum=", x),
                 paste0("&company=", URLencode(x, reserved = TRUE))),
          ifelse(file_number,
                 paste0("&CIK=&filenum=", x),
                 paste0("&CIK=", URLencode(x, reserved = TRUE)))
           )

I was not able to get it testable, so I don't know:
- if indeed the api would accept the CIK-fie;d
- how CIK and filenum have to interact, which combinations are compatible

Again, would love to have this implemented!

**Comment by mwaldstein** [comment]
If you already have a CIK or ticker, you can jump straight to using `company_information`, which is effectively how the fast search form works.

The 'Fast Search' form under the hood isn't really a search at all, rather a "get" function that either returns a company or doesn't which is why it isn't used in the `company_search` function.

**Comment by proverbs53** [comment]
Thanks for the swift reply! 
I do actually have ticker symbols, and looking for a way how to resolve those against CIK's in cases where a company did change CIK numbers. I hoped/assumed that there would be scenarios in which one ticker would resolve to multiple CIK numbers. What I understand is that Fast Search would not tackle that scenario.

**Comment by mwaldstein** [comment]
I'd suggest testing it out using the webpage - I certainly may be mistaken about how those components work. 

I'm going to keep this issue open as a tracker to document how 'Fast Search' works and how to use it in edgarWebR.

Appreciate the feedback!

**Comment by proverbs53** [comment]
Hi Micah,

I'm now enjoying a two week holiday. Will get back to this in September. Thanks for leaving the request open for now!

Freddy

Op 16 aug. 2018 om 15:34 heeft Micah J Waldstein <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'd suggest testing it out using the webpage - I certainly may be mistaken about how those components work.

I'm going to keep this issue open as a tracker to document how 'Fast Search' works and how to use it in edgarWebR.

Appreciate the feedback!

**Comment by mwaldstein** [comment]
I documented how 'fast search' works in the documentation for 'Company Search'. Feel free to open another issue if you find another gap.
